language: python
python:
  - "2.7"

sudo: false

env:
  global:
    - PIP_FIND_LINKS=file://$HOME/.cache/pip
    - PIP_CACHE_DIR=$HOME/.cache/pip

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install tox

script:
  - tox
  # Remove logs to avoid cache uploads
  - rm -rf $HOME/.cache/pip/log

after_script:
  - tox -e py27-coveralls

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# please comment out this section in your personal fork!
notifications:
  irc:
    channels:
      - "irc.mozilla.org#releng"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
