language: python
python:
  - "2.7"

install:
  - pip install tox

script:
  - tox -e py27,py27-coveralls

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc: "irc.mozilla.org#releng"
  on_success: always
  on_failure: always
